security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main: 
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginAuthenticator
            entry_point: form_login  
            form_login:
                login_path: login
                check_path: login
                default_target_path: home
                enable_csrf: true
            logout:
                path: app_logout
                target: login

    access_control:
       - { path: ^/login, roles: PUBLIC_ACCESS }
       - { path: ^/register, roles: PUBLIC_ACCESS }
       - { path: ^/$, roles: PUBLIC_ACCESS }  
       - { path: ^/admin, roles: ROLE_ADMIN }
       - { path: ^/, roles: ROLE_USER }

